/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.diagrama;

import br.edu.ifpr.thecoxinhagame.conexao.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author Aluno
 */
public class CampoDeBatalha extends javax.swing.JFrame {

    private Guerreira guerreira;
    private Mago mago;

    /**
     * Creates new form CadastroPersonagem
     */
    public CampoDeBatalha() {
        initComponents();
        mostrarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        Comecar = new javax.swing.JButton();
        txtVida = new javax.swing.JTextField();
        txtAtaque = new javax.swing.JTextField();
        txtDefesa = new javax.swing.JTextField();
        txtForca = new javax.swing.JTextField();
        txtTeste = new javax.swing.JTextField();
        txtNomeM = new javax.swing.JTextField();
        txtVidaM = new javax.swing.JTextField();
        txtAtaqueM = new javax.swing.JTextField();
        txtDefesaM = new javax.swing.JTextField();
        txtInteligencia = new javax.swing.JTextField();
        txtRecuperacao = new javax.swing.JTextField();
        txtVelocidade1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(865, 525));
        setMinimumSize(new java.awt.Dimension(865, 525));
        setPreferredSize(new java.awt.Dimension(865, 525));
        setResizable(false);
        setSize(new java.awt.Dimension(865, 525));
        getContentPane().setLayout(null);

        txtNome.setEditable(false);
        txtNome.setText("Phoebe");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(20, 220, 190, 22);

        Comecar.setText("Começar");
        Comecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComecarActionPerformed(evt);
            }
        });
        getContentPane().add(Comecar);
        Comecar.setBounds(370, 460, 140, 20);

        txtVida.setEditable(false);
        txtVida.setText("100");
        txtVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVidaActionPerformed(evt);
            }
        });
        getContentPane().add(txtVida);
        txtVida.setBounds(20, 250, 190, 22);

        txtAtaque.setEditable(false);
        txtAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtaqueActionPerformed(evt);
            }
        });
        getContentPane().add(txtAtaque);
        txtAtaque.setBounds(20, 280, 190, 22);

        txtDefesa.setEditable(false);
        txtDefesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDefesaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDefesa);
        txtDefesa.setBounds(20, 310, 190, 22);

        txtForca.setEditable(false);
        txtForca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtForcaActionPerformed(evt);
            }
        });
        getContentPane().add(txtForca);
        txtForca.setBounds(20, 340, 190, 22);

        txtTeste.setEditable(false);
        txtTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTesteActionPerformed(evt);
            }
        });
        getContentPane().add(txtTeste);
        txtTeste.setBounds(20, 440, 190, 22);

        txtNomeM.setEditable(false);
        txtNomeM.setText("Saori");
        txtNomeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeM);
        txtNomeM.setBounds(650, 230, 190, 22);

        txtVidaM.setEditable(false);
        txtVidaM.setText("100");
        txtVidaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVidaMActionPerformed(evt);
            }
        });
        getContentPane().add(txtVidaM);
        txtVidaM.setBounds(650, 260, 190, 22);

        txtAtaqueM.setEditable(false);
        txtAtaqueM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtaqueMActionPerformed(evt);
            }
        });
        getContentPane().add(txtAtaqueM);
        txtAtaqueM.setBounds(650, 290, 190, 22);

        txtDefesaM.setEditable(false);
        txtDefesaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDefesaMActionPerformed(evt);
            }
        });
        getContentPane().add(txtDefesaM);
        txtDefesaM.setBounds(650, 320, 190, 22);

        txtInteligencia.setEditable(false);
        txtInteligencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInteligenciaActionPerformed(evt);
            }
        });
        getContentPane().add(txtInteligencia);
        txtInteligencia.setBounds(650, 350, 190, 22);

        txtRecuperacao.setEditable(false);
        txtRecuperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecuperacaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtRecuperacao);
        txtRecuperacao.setBounds(650, 380, 190, 22);

        txtVelocidade1.setEditable(false);
        txtVelocidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVelocidade1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtVelocidade1);
        txtVelocidade1.setBounds(20, 370, 190, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fundoOF2.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(853, 500));
        jLabel2.setMinimumSize(new java.awt.Dimension(853, 500));
        jLabel2.setPreferredSize(new java.awt.Dimension(853, 500));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 850, 490);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 430, 71, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed

    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVidaActionPerformed

    }//GEN-LAST:event_txtVidaActionPerformed

    private void txtNomeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMActionPerformed

    }//GEN-LAST:event_txtNomeMActionPerformed

    private void txtVidaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVidaMActionPerformed

    }//GEN-LAST:event_txtVidaMActionPerformed

    private void txtDefesaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDefesaMActionPerformed

    }//GEN-LAST:event_txtDefesaMActionPerformed

    private void txtAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtaqueActionPerformed

    }//GEN-LAST:event_txtAtaqueActionPerformed

    private void ComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComecarActionPerformed
        realizarRodada();
    }//GEN-LAST:event_ComecarActionPerformed

    private void txtDefesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDefesaActionPerformed

    }//GEN-LAST:event_txtDefesaActionPerformed

    private void txtForcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtForcaActionPerformed

    }//GEN-LAST:event_txtForcaActionPerformed

    private void txtTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTesteActionPerformed

    }//GEN-LAST:event_txtTesteActionPerformed

    private void txtAtaqueMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtaqueMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtaqueMActionPerformed

    private void txtInteligenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInteligenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInteligenciaActionPerformed

    private void txtRecuperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecuperacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecuperacaoActionPerformed

    private void txtVelocidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVelocidade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVelocidade1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampoDeBatalha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comecar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtAtaque;
    private javax.swing.JTextField txtAtaqueM;
    private javax.swing.JTextField txtDefesa;
    private javax.swing.JTextField txtDefesaM;
    private javax.swing.JTextField txtForca;
    private javax.swing.JTextField txtInteligencia;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeM;
    private javax.swing.JTextField txtRecuperacao;
    private javax.swing.JTextField txtTeste;
    private javax.swing.JTextField txtVelocidade1;
    private javax.swing.JTextField txtVida;
    private javax.swing.JTextField txtVidaM;
    // End of variables declaration//GEN-END:variables

    private void mostrarDados() {
        mago = buscarMagoNoBanco();

        txtNomeM.setText(mago.getNome());
        txtVidaM.setText("" + mago.getPontosVida());
        txtAtaqueM.setText("" + mago.getPontosAtaque());
        txtDefesaM.setText("" + mago.getPontosDefesa());
        txtInteligencia.setText("" + mago.getInteligencia());
        txtRecuperacao.setText("" + mago.getRecuperacao());

        guerreira = buscarGuerreiraNoBanco();

        txtNome.setText(guerreira.getNome());
        txtVida.setText("" + guerreira.getPontosVida());
        txtAtaque.setText("" + guerreira.getPontosAtaque());
        txtDefesa.setText("" + guerreira.getPontosDefesa());
        txtForca.setText("" + guerreira.getForca());
        txtTeste.setText("" + guerreira.getVelocidade());
    }
    
    
    private void realizarRodada() {
        int danoGuerreira = guerreira.atacar();
        mago.receberDano(danoGuerreira);
        
        int inicial = (int) (Math.random());
        
        

        if (mago.getPontosVida() <= 0) {
            JOptionPane.showMessageDialog(this, guerreira.getNome() + " venceu a batalha!");
            System.exit(0);
        }

        int danoMago = mago.conjurarMagia();
        guerreira.receberDano(danoMago);
        //exibirDadosPersonagem(txtNome, guerreira);

        if (guerreira.getPontosVida() <= 0) {
            JOptionPane.showMessageDialog(this, mago.getNome() + " venceu a batalha!");
            System.exit(0);
        }
    }

    private Mago buscarMagoNoBanco() {
         Mago mago = new Mago();
        
        String sql = "SELECT * FROM `tb_mago` ORDER BY id_mago DESC LIMIT 1;";
        
        
        
        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            ResultSet resultado = preparacaoDaInstrucao.executeQuery();
            resultado.next();
            
            mago.setNome(resultado.getString("nome"));
            mago.setPontosVida(resultado.getInt("ponto_vida"));
            mago.setPontosAtaque(resultado.getInt("ponto_ataque"));
            mago.setPontosDefesa(resultado.getInt("ponto_defesa"));
            mago.setInteligencia(resultado.getInt("inteligencia"));
            mago.setRecuperacao(resultado.getInt("recuperacao"));
        } catch (SQLException ex) {
            Logger.getLogger(VerMago.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        return mago;
    }

    private Guerreira buscarGuerreiraNoBanco() {
        Guerreira guerreira = new Guerreira();
        
        String sql = "SELECT * FROM `tb_guerreira` ORDER BY id_guerreira DESC LIMIT 1;";
        
        
        
        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            ResultSet resultado = preparacaoDaInstrucao.executeQuery();
            resultado.next();
            
            guerreira.setNome(resultado.getString("nome"));
            guerreira.setPontosVida(resultado.getInt("ponto_vida"));
            guerreira.setPontosAtaque(resultado.getInt("ponto_ataque"));
            guerreira.setPontosDefesa(resultado.getInt("ponto_defesa"));
            guerreira.setForca(resultado.getInt("forca"));
            guerreira.setVelocidade(resultado.getInt("velocidade"));
        } catch (SQLException ex) {
            Logger.getLogger(VerGuerreira.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        return guerreira;
    }
}
