/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.diagrama;

/**
 *
 * @author Aluno
 */
public class TelaDeCadastro extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPersonagem
     */
    public TelaDeCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroGuerreira = new javax.swing.JButton();
        CadastroMago = new javax.swing.JButton();
        Batalha = new javax.swing.JButton();
        CadastroItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        CadastroGuerreira.setText("Cadastro Guerreira");
        CadastroGuerreira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroGuerreiraActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroGuerreira);
        CadastroGuerreira.setBounds(10, 50, 130, 23);

        CadastroMago.setText("Cadastro Mago");
        CadastroMago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroMagoActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroMago);
        CadastroMago.setBounds(10, 20, 130, 23);

        Batalha.setText("Batalha");
        getContentPane().add(Batalha);
        Batalha.setBounds(40, 120, 72, 23);

        CadastroItem.setText("Cadastro de Item");
        CadastroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroItemActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroItem);
        CadastroItem.setBounds(10, 80, 130, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroMagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroMagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroMagoActionPerformed

    private void CadastroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroItemActionPerformed

    private void CadastroGuerreiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroGuerreiraActionPerformed
        CadastroGuerreira cadastroGuerreira = new CadastroGuerreira();
        cadastroGuerreira.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CadastroGuerreiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batalha;
    private javax.swing.JButton CadastroGuerreira;
    private javax.swing.JButton CadastroItem;
    private javax.swing.JButton CadastroMago;
    // End of variables declaration//GEN-END:variables
}
