/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.diagrama;

/**
 *
 * @author Aluno
 */
public class TelaDeCadastro extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPersonagem
     */
    public TelaDeCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CadastroGuerreira = new javax.swing.JButton();
        CadastroMago = new javax.swing.JButton();
        Batalha = new javax.swing.JButton();
        CadastroItem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/FUNDOSSS.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(440, 470));
        setMinimumSize(new java.awt.Dimension(440, 470));
        setPreferredSize(new java.awt.Dimension(440, 470));
        setSize(new java.awt.Dimension(440, 470));
        getContentPane().setLayout(null);

        CadastroGuerreira.setText("Cadastro Guerreira");
        CadastroGuerreira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroGuerreiraActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroGuerreira);
        CadastroGuerreira.setBounds(90, 150, 240, 50);

        CadastroMago.setText("Cadastro Mago");
        CadastroMago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroMagoActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroMago);
        CadastroMago.setBounds(90, 80, 240, 50);

        Batalha.setText("Batalha");
        Batalha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalhaActionPerformed(evt);
            }
        });
        getContentPane().add(Batalha);
        Batalha.setBounds(150, 290, 120, 70);

        CadastroItem.setText("Cadastro de Item");
        CadastroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroItemActionPerformed(evt);
            }
        });
        getContentPane().add(CadastroItem);
        CadastroItem.setBounds(90, 220, 240, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/FUNDOSSS.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 430, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastroMagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroMagoActionPerformed
        CadastroMago cadastroMago = new CadastroMago();
        cadastroMago.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CadastroMagoActionPerformed

    private void CadastroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroItemActionPerformed
        CadastroItem cadastroItem = new CadastroItem();
        cadastroItem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CadastroItemActionPerformed

    private void CadastroGuerreiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroGuerreiraActionPerformed
        CadastroGuerreira cadastroGuerreira = new CadastroGuerreira();
        cadastroGuerreira.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CadastroGuerreiraActionPerformed

    private void BatalhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalhaActionPerformed
        CampoDeBatalha campoDeBatalha = new CampoDeBatalha();
        campoDeBatalha.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BatalhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batalha;
    private javax.swing.JButton CadastroGuerreira;
    private javax.swing.JButton CadastroItem;
    private javax.swing.JButton CadastroMago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
