package br.edu.ifpr.diagrama;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import br.edu.ifpr.thecoxinhagame.conexao.Conexao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Aluno
 */
public class VerGuerreira extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPersonagem
     */
    public VerGuerreira() {
        initComponents();
        
        Guerreira guerreira = buscarGuerreira();
        
        txtNome.setText(guerreira.getNome());
        
        int ataque = guerreira.getPontosAtaque();
        txtPontosAtaque.setText("" + ataque);

        int defesa = guerreira.getPontosDefesa();
        txtPontosDefesa.setText("" + defesa);

        int forca = guerreira.getForca();
        txtForca.setText("" + forca);

        int velocidade = guerreira.getVelocidade();
        txtVelocidade.setText("" + velocidade);
        
        imprimeGuerreiras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        txtPontosVida = new javax.swing.JLabel();
        Ataque = new javax.swing.JLabel();
        Defesa = new javax.swing.JLabel();
        Forca = new javax.swing.JLabel();
        Velocidade = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        salvar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtVelocidade = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        txtPontosAtaque = new javax.swing.JTextField();
        txtPontosDefesa = new javax.swing.JTextField();
        txtForca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Nome.setText("Nome:");
        getContentPane().add(Nome);
        Nome.setBounds(10, 10, 36, 16);

        txtPontosVida.setText("Pontos de Vida");
        getContentPane().add(txtPontosVida);
        txtPontosVida.setBounds(10, 70, 79, 16);

        Ataque.setText("Pontos de Ataque");
        getContentPane().add(Ataque);
        Ataque.setBounds(10, 130, 94, 16);

        Defesa.setText("Pontos de Defesa");
        getContentPane().add(Defesa);
        Defesa.setBounds(10, 190, 91, 16);

        Forca.setText("Força:");
        getContentPane().add(Forca);
        Forca.setBounds(10, 250, 32, 16);

        Velocidade.setText("Velocidade:");
        getContentPane().add(Velocidade);
        Velocidade.setBounds(10, 310, 61, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/guerreiro fofo.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 60, 230, 250);

        salvar.setText("Salvar Guerreira");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        getContentPane().add(salvar);
        salvar.setBounds(140, 380, 140, 30);

        txtNome.setText("Phoebe");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(10, 30, 170, 22);

        txtVelocidade.setEditable(false);
        getContentPane().add(txtVelocidade);
        txtVelocidade.setBounds(10, 330, 170, 22);

        jTextField3.setEditable(false);
        jTextField3.setText("100");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(10, 90, 170, 22);

        txtPontosAtaque.setEditable(false);
        txtPontosAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPontosAtaqueActionPerformed(evt);
            }
        });
        getContentPane().add(txtPontosAtaque);
        txtPontosAtaque.setBounds(10, 150, 170, 22);

        txtPontosDefesa.setEditable(false);
        getContentPane().add(txtPontosDefesa);
        txtPontosDefesa.setBounds(10, 210, 170, 22);

        txtForca.setEditable(false);
        txtForca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtForcaActionPerformed(evt);
            }
        });
        getContentPane().add(txtForca);
        txtForca.setBounds(10, 270, 170, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
         Guerreira guerreira = new Guerreira();

        guerreira.setNome(txtNome.getText());
        guerreira.setPontosVida(Integer.parseInt(txtPontosVida.getText()));
        guerreira.setPontosAtaque(Integer.parseInt(txtPontosAtaque.getText()));
        guerreira.setPontosDefesa(Integer.parseInt(txtPontosDefesa.getText()));
        guerreira.setForca(Integer.parseInt(txtForca.getText()));
        guerreira.setVelocidade(Integer.parseInt(txtVelocidade.getText()));

        salvar(guerreira);
    }//GEN-LAST:event_salvarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPontosAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPontosAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontosAtaqueActionPerformed

    private void txtForcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtForcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtForcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerGuerreira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ataque;
    private javax.swing.JLabel Defesa;
    private javax.swing.JLabel Forca;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Velocidade;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField txtForca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPontosAtaque;
    private javax.swing.JTextField txtPontosDefesa;
    private javax.swing.JLabel txtPontosVida;
    private javax.swing.JTextField txtVelocidade;
    // End of variables declaration//GEN-END:variables

     private void salvar(Guerreira guerreira) {
        String sql = "INSERT "
                + "INTO `tb_guerreiro` "
                + "(`nome`, `ponto_vida`, `ponto_ataque`, `ponto_defesa`, `forca`, `velocidade`) "
                + "VALUES "
                + "(?, ?, ?, ?, ?, ?);";
        try {
                PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
                preparacaoDaInstrucao.setString(1, guerreira.getNome());
                preparacaoDaInstrucao.setInt(2, guerreira.getPontosVida());
                preparacaoDaInstrucao.setInt(3, guerreira.getPontosAtaque());
                preparacaoDaInstrucao.setInt(4, guerreira.getPontosDefesa());
                preparacaoDaInstrucao.setInt(5, guerreira.getForca());
                preparacaoDaInstrucao.setInt(6, guerreira.getVelocidade());
                preparacaoDaInstrucao.executeUpdate();
                JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
                this.dispose(); // libera a memória da janela
                new TelaDeCadastro().setVisible(true); // exibe a tela inicial
        } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao salvar!");
        }
    }
     
     private Guerreira buscarGuerreira() {
        
        Guerreira guerreira = new Guerreira();
        
        String sql = "SELECT * FROM `tb_guerreira`;";
        
        
        
        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            ResultSet resultado = preparacaoDaInstrucao.executeQuery();
            resultado.next();
            
            guerreira.setNome(resultado.getString("nome"));
            guerreira.setPontosVida(resultado.getInt("ponto_vida"));
            guerreira.setPontosAtaque(resultado.getInt("ponto_ataque"));
            guerreira.setPontosDefesa(resultado.getInt("ponto_defesa"));
            guerreira.setForca(resultado.getInt("forca"));
            guerreira.setVelocidade(resultado.getInt("velocidade"));
        } catch (SQLException ex) {
            Logger.getLogger(VerGuerreira.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        return guerreira;
    }
    
    private void imprimeGuerreiras() {
        
        Guerreira guerreira = new Guerreira();
        
        String sql = "SELECT * FROM `tb_guerreiro`;";
        
        
        
        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            ResultSet resultado = preparacaoDaInstrucao.executeQuery();
            
            while(resultado.next()){
                guerreira.setNome(resultado.getString("nome"));
                guerreira.setPontosVida(resultado.getInt("ponto_vida"));
                guerreira.setPontosAtaque(resultado.getInt("ponto_ataque"));
                guerreira.setPontosDefesa(resultado.getInt("ponto_defesa"));
                guerreira.setForca(resultado.getInt("forca"));
                guerreira.setVelocidade(resultado.getInt("velocidade"));
                System.out.println(guerreira.toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerGuerreira.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }
}
